version: "3.9"

services:
    backend:
        container_name: awale_backend
        build: awale-backend/
        ports:
            - "63221:80"
        networks:
            - awale-network

    frontend:
        container_name: awale_frontend
        build: awale-frontend/
        depends_on:
            - backend
        ports:
            - "8080:80"
        networks:
            - awale-network
        logging:
            driver: none

networks:
    awale-network:
        driver: bridge
